language: objective-c
script: "xcodebuild -project traviscitest.xcodeproj -scheme traviscitest -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' clean test | xcpretty -c && exit ${PIPESTATUS[0]}"