language: objective-c
script: xctool test -project traviscitest.xcodeproj -scheme traviscitest -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6'
# osx_image: xcode7.2
# xcode_project: traviscitest.xcodeproj
# xcode_scheme: traviscitest
# xcode_sdk: iphonesimulator9.2